const baseContract = {
    title: null,
    sub_title: null,
    slug: null,
    type: null,
    ucid: null,
    status: null,
    value: null,
    ss_leads: [],
    need_date: null,
    award_date: null,
    cycle_code: null,
    pop_date: null,
    g_o_p: null,
    g_t_p: null,
    g_tr_p: null,
    g_fr_o_p: null,
    g_fr_t_p: null,
    g_fr_tr_p: null,
    g_fr_fr_p: null,
    g_fr_fv_p: null,
    pco: null,
    buyer: null,
    admin_pco: null,
    admin_buyer: null,
    pocs: [],
    tasks: [
        {
            title: 'Identify / Validate Need',
            sub_title: null,
            slug: 'identify-validate-need',
            status: 'IC',
            order_id: 1,
            gate: 1,
            sub_gate: null,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'Identify issues, requirements, needs',
                    sub_title: null,
                    slug: 'identify-issues-requirements-needs',
                    status: 'IC',
                    order_id: 2,
                    gate: 1,
                    sub_gate: null,
                    palt_plan: 1.0,
                    bus_days: 1.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Establish need and technical review/ dates',
                    sub_title: null,
                    slug: 'establish-need-and-technical-review-dates',
                    status: 'IC',
                    order_id: 3,
                    gate: 1,
                    sub_gate: null,
                    palt_plan: 0.5,
                    bus_days: 0.5,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Organic vs. contract',
                    sub_title: null,
                    slug: 'organic-vs-contract',
                    status: 'IC',
                    order_id: 4,
                    gate: 1,
                    sub_gate: null,
                    palt_plan: 0.5,
                    bus_days: 0.5,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: '50/50 (Document showing concurrence from DV)',
                    sub_title: null,
                    slug: '5050-document-showing-concurrence-from-dv',
                    status: 'IC',
                    order_id: 5,
                    gate: 1,
                    sub_gate: null,
                    palt_plan: 1.0,
                    bus_days: 1.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Funding Outlook',
                    sub_title: null,
                    slug: 'funding-outlook',
                    status: 'IC',
                    order_id: 6,
                    gate: 1,
                    sub_gate: null,
                    palt_plan: 0.5,
                    bus_days: 0.5,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'RAD if required submitted (Can be done in gate 2/3)',
                    sub_title: null,
                    slug: 'rad-if-required-submitted-can-be-done-in-gate-23',
                    status: 'IC',
                    order_id: 7,
                    gate: 1,
                    sub_gate: null,
                    palt_plan: 1.0,
                    bus_days: 1.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Submit RIW thru AMSO site',
                    sub_title: null,
                    slug: 'submit-riw-thru-amso-site',
                    status: 'IC',
                    order_id: 8,
                    gate: 1,
                    sub_gate: null,
                    palt_plan: 0.5,
                    bus_days: 0.5,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Outline Preliminary Sourcing Approach',
            sub_title: null,
            slug: 'outline-preliminary-sourcing-approach',
            status: 'IC',
            order_id: 9,
            gate: 2,
            sub_gate: null,
            palt_plan: 15.0,
            bus_days: 15.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'Identify Key stakeholders/ MFT members',
                    sub_title: null,
                    slug: 'identify-key-stakeholders-mft-members',
                    status: 'IC',
                    order_id: 10,
                    gate: 2,
                    sub_gate: null,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Cost Benefit Analysis if necessary/ MIPR or Local',
                    sub_title: null,
                    slug: 'cost-benefit-analysis-if-necessary-mipr-or-local',
                    status: 'IC',
                    order_id: 11,
                    gate: 2,
                    sub_gate: null,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Sourcing (i.e. are there enterprise contracts in existence)',
                    sub_title: null,
                    slug: 'sourcing-ie-are-there-enterprise-contracts-in-existence',
                    status: 'IC',
                    order_id: 12,
                    gate: 2,
                    sub_gate: null,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Begin Market Research',
                    sub_title: null,
                    slug: 'begin-market-research',
                    status: 'IC',
                    order_id: 13,
                    gate: 2,
                    sub_gate: null,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Spend Analysis',
                    sub_title: null,
                    slug: 'spend-analysis',
                    status: 'IC',
                    order_id: 14,
                    gate: 2,
                    sub_gate: null,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Identify Risks',
                    sub_title: null,
                    slug: 'identify-risks',
                    status: 'IC',
                    order_id: 15,
                    gate: 2,
                    sub_gate: null,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'POM if necessary',
                    sub_title: null,
                    slug: 'pom-if-necessary',
                    status: 'IC',
                    order_id: 16,
                    gate: 2,
                    sub_gate: null,
                    palt_plan: 1.0,
                    bus_days: 1.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Finalize MFT members',
                    sub_title: null,
                    slug: 'finalize-mft-members',
                    status: 'IC',
                    order_id: 17,
                    gate: 2,
                    sub_gate: null,
                    palt_plan: 1.0,
                    bus_days: 1.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Prepare Strategy Outline Summary (SOS)',
                    sub_title: null,
                    slug: 'prepare-strategy-outline-summary-sos',
                    status: 'IC',
                    order_id: 18,
                    gate: 2,
                    sub_gate: null,
                    palt_plan: 1.0,
                    bus_days: 1.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Purchase Request Preparation',
            sub_title: null,
            slug: 'purchase-request-preparation',
            status: 'IC',
            order_id: 19,
            gate: 3,
            sub_gate: null,
            palt_plan: 58.0,
            bus_days: 58.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Identify Team Members',
            sub_title: null,
            slug: 'identify-team-members',
            status: 'IC',
            order_id: 20,
            gate: 3,
            sub_gate: null,
            palt_plan: 0.5,
            bus_days: 0.5,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Kick-Off MFT Meeting',
            sub_title: null,
            slug: 'kickoff-mft-meeting',
            status: 'IC',
            order_id: 21,
            gate: 3,
            sub_gate: null,
            palt_plan: 2.0,
            bus_days: 2.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: "Req't Meeting with Stakeholders",
            sub_title: null,
            slug: 'reqt-meeting-with-stakeholders',
            status: 'IC',
            order_id: 22,
            gate: 3,
            sub_gate: null,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Begin Developing Draft Docs (see list)',
            sub_title: null,
            slug: 'begin-developing-draft-docs-see-list',
            status: 'IC',
            order_id: 23,
            gate: 3,
            sub_gate: null,
            palt_plan: 30.0,
            bus_days: 30.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'Requirements Approval Document (Services)',
                    sub_title: null,
                    slug: 'requirements-approval-document-services',
                    status: 'IC',
                    order_id: 24,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 7.5,
                    bus_days: 7.5,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'RIW (309th only)',
                    sub_title: null,
                    slug: 'riw-309th-only',
                    status: 'IC',
                    order_id: 25,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 7.5,
                    bus_days: 7.5,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Begin drafting PWS / SOW / SOO',
                    sub_title: null,
                    slug: 'begin-drafting-pws-sow-soo',
                    status: 'IC',
                    order_id: 26,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 7.5,
                    bus_days: 7.5,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Cost Estimate',
                    sub_title: null,
                    slug: 'cost-estimate',
                    status: 'IC',
                    order_id: 27,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 7.5,
                    bus_days: 7.5,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Schedule Phase I Training',
            sub_title: null,
            slug: 'schedule-phase-i-training',
            status: 'IC',
            order_id: 28,
            gate: 3,
            sub_gate: null,
            palt_plan: 0.5,
            bus_days: 0.5,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Develop Cost Estimate w/FM',
            sub_title: null,
            slug: 'develop-cost-estimate-wfm',
            status: 'IC',
            order_id: 29,
            gate: 3,
            sub_gate: null,
            palt_plan: 20.0,
            bus_days: 20.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Market Research',
            sub_title: null,
            slug: 'market-research',
            status: 'IC',
            order_id: 30,
            gate: 3,
            sub_gate: null,
            palt_plan: 156.0,
            bus_days: 156.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'Develop Market Research Report',
                    sub_title: null,
                    slug: 'develop-market-research-report',
                    status: 'IC',
                    order_id: 31,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 17.0,
                    bus_days: 17.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Prepare Docs for RFI',
                    sub_title: null,
                    slug: 'prepare-docs-for-rfi',
                    status: 'IC',
                    order_id: 32,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 10.0,
                    bus_days: 10.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Conduct Risk Assessment',
                    sub_title: null,
                    slug: 'conduct-risk-assessment',
                    status: 'IC',
                    order_id: 33,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 1.0,
                    bus_days: 1.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Conduct Risk Mitigation (see line 56)',
                    sub_title: null,
                    slug: 'conduct-risk-mitigation-see-line-56',
                    status: 'IC',
                    order_id: 34,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 1.0,
                    bus_days: 1.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Post RFI',
                    sub_title: null,
                    slug: 'post-rfi',
                    status: 'IC',
                    order_id: 35,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 15.0,
                    bus_days: 15.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Review RFI Responses',
                    sub_title: null,
                    slug: 'review-rfi-responses',
                    status: 'IC',
                    order_id: 36,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 10.0,
                    bus_days: 10.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Post RFI #2',
                    sub_title: null,
                    slug: 'post-rfi-2',
                    status: 'IC',
                    order_id: 37,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 20.0,
                    bus_days: 20.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Review RFI #2 Responses',
                    sub_title: null,
                    slug: 'review-rfi-2-responses',
                    status: 'IC',
                    order_id: 38,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 20.0,
                    bus_days: 20.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Prep for Industry Day - This was not held.',
                    sub_title: null,
                    slug: 'prep-for-industry-day-this-was-not-held',
                    status: 'IC',
                    order_id: 39,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 15.0,
                    bus_days: 15.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Hold Industry Day - This was not held.',
                    sub_title: null,
                    slug: 'hold-industry-day-this-was-not-held',
                    status: 'IC',
                    order_id: 40,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 1.0,
                    bus_days: 1.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Market Research Report Signed',
                    sub_title: null,
                    slug: 'market-research-report-signed',
                    status: 'IC',
                    order_id: 41,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 1.0,
                    bus_days: 1.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: '(Draft Sections L&M and be ready for Draft RFP Release after AP approval)',
                    sub_title: null,
                    slug: 'draft-sections-lm-and-be-ready-for-draft-rfp-release-after-ap-approval',
                    status: 'IC',
                    order_id: 42,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 45.0,
                    bus_days: 45.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Acquisition Strategy',
            sub_title: null,
            slug: 'acquisition-strategy',
            status: 'IC',
            order_id: 43,
            gate: 3,
            sub_gate: null,
            palt_plan: 344.0,
            bus_days: 344.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Prepare all Acq Strategy Docs (see list)',
            sub_title: null,
            slug: 'prepare-all-acq-strategy-docs-see-list',
            status: 'IC',
            order_id: 44,
            gate: 3,
            sub_gate: null,
            palt_plan: 164.0,
            bus_days: 164.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'Acquisition Plan (Pending LPTA or TRADEOFF decision)',
                    sub_title: null,
                    slug: 'acquisition-plan-pending-lpta-or-tradeoff-decision',
                    status: 'IC',
                    order_id: 45,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 25.0,
                    bus_days: 25.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'ASP Briefing Charts',
                    sub_title: null,
                    slug: 'asp-briefing-charts',
                    status: 'IC',
                    order_id: 46,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 20.0,
                    bus_days: 20.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Draft PWS / SOW / SOO',
                    sub_title: null,
                    slug: 'draft-pws-sow-soo',
                    status: 'IC',
                    order_id: 47,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 25.0,
                    bus_days: 25.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Draft Source Selection Plan (Need L&M but not the rest of the SSP)',
                    sub_title: null,
                    slug: 'draft-source-selection-plan-need-lm-but-not-the-rest-of-the-ssp',
                    status: 'IC',
                    order_id: 48,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 25.0,
                    bus_days: 25.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'SSA Delegation Letter (if applicable)',
                    sub_title: null,
                    slug: 'ssa-delegation-letter-if-applicable',
                    status: 'IC',
                    order_id: 49,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 25.0,
                    bus_days: 25.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Small Business Coordination DD2579',
                    sub_title: null,
                    slug: 'small-business-coordination-dd2579',
                    status: 'IC',
                    order_id: 50,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 22.0,
                    bus_days: 22.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Draft and Planner PR',
                    sub_title: null,
                    slug: 'draft-and-planner-pr',
                    status: 'IC',
                    order_id: 51,
                    gate: 3,
                    sub_gate: null,
                    palt_plan: 22.0,
                    bus_days: 22.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Prepare briefing charts for ESIS',
            sub_title: null,
            slug: 'prepare-briefing-charts-for-esis',
            status: 'IC',
            order_id: 52,
            gate: 0,
            sub_gate: null,
            palt_plan: null,
            bus_days: null,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Schedule Time for ESIS',
            sub_title: null,
            slug: 'schedule-time-for-esis',
            status: 'IC',
            order_id: 53,
            gate: 0,
            sub_gate: null,
            palt_plan: null,
            bus_days: null,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Brief ESIS (over $100M)',
            sub_title: null,
            slug: 'brief-esis-over-100m',
            status: 'IC',
            order_id: 54,
            gate: 0,
            sub_gate: null,
            palt_plan: null,
            bus_days: null,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Legal Review ',
            sub_title: null,
            slug: 'legal-review',
            status: 'IC',
            order_id: 55,
            gate: 3,
            sub_gate: null,
            palt_plan: 20.0,
            bus_days: 20.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Pre-ASP Committee Review',
            sub_title: null,
            slug: 'preasp-committee-review',
            status: 'IC',
            order_id: 56,
            gate: 3,
            sub_gate: null,
            palt_plan: 20.0,
            bus_days: 20.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Small Business Review',
            sub_title: null,
            slug: 'small-business-review',
            status: 'IC',
            order_id: 57,
            gate: 0,
            sub_gate: null,
            palt_plan: null,
            bus_days: null,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Pre-ASP Supervisor & Branch Chief Review (PK & OBC/AMSO)Pogue',
            sub_title: null,
            slug: 'preasp-supervisor-branch-chief-review-pk-obcamsopogue',
            status: 'IC',
            order_id: 58,
            gate: 3,
            sub_gate: null,
            palt_plan: 20.0,
            bus_days: 20.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Schedule Time for ASP/ Resolve comments (Kailey N. to schedule w/ Mr. Jessen)',
            sub_title: null,
            slug: 'schedule-time-for-asp-resolve-comments-kailey-n-to-schedule-w-mr-jessen',
            status: 'IC',
            order_id: 59,
            gate: 3,
            sub_gate: null,
            palt_plan: 80.0,
            bus_days: 80.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'ASP Briefing',
            sub_title: null,
            slug: 'asp-briefing',
            status: 'IC',
            order_id: 60,
            gate: 3,
            sub_gate: null,
            palt_plan: 20.0,
            bus_days: 20.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Acq Strategy Signed',
            sub_title: null,
            slug: 'acq-strategy-signed',
            status: 'IC',
            order_id: 61,
            gate: 3,
            sub_gate: null,
            palt_plan: 20.0,
            bus_days: 20.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Prepare for RFP Release',
            sub_title: null,
            slug: 'prepare-for-rfp-release',
            status: 'IC',
            order_id: 62,
            gate: 4,
            sub_gate: 1,
            palt_plan: 20.0,
            bus_days: 20.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Post Draft RFP and Docs',
            sub_title: null,
            slug: 'post-draft-rfp-and-docs',
            status: 'IC',
            order_id: 63,
            gate: 4,
            sub_gate: 1,
            palt_plan: 4.0,
            bus_days: 4.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Finalize the following docs and training(s) for RFP:',
            sub_title: null,
            slug: 'finalize-the-following-docs-and-trainings-for-rfp',
            status: 'IC',
            order_id: 64,
            gate: 4,
            sub_gate: 1,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'Draft PWS/SOW/SOO',
                    sub_title: null,
                    slug: 'draft-pwssowsoo',
                    status: 'IC',
                    order_id: 65,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Draft Source Selection Plan & eSSS (includes Sections L&M)',
                    sub_title: null,
                    slug: 'draft-source-selection-plan-esss-includes-sections-lm',
                    status: 'IC',
                    order_id: 66,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'SSA Delegation Letter (if applicable)',
                    sub_title: null,
                    slug: 'ssa-delegation-letter-if-applicable',
                    status: 'IC',
                    order_id: 67,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Clearance Request Form',
                    sub_title: null,
                    slug: 'clearance-request-form',
                    status: 'IC',
                    order_id: 68,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Ensure e-File is completed and moved to the A Drive',
                    sub_title: null,
                    slug: 'ensure-efile-is-completed-and-moved-to-the-a-drive',
                    status: 'IC',
                    order_id: 69,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'EZSource DD2579 Access Request Forms (Can be completed after RFP Release)',
                    sub_title: null,
                    slug: 'ezsource-dd2579-access-request-forms-can-be-completed-after-rfp-release',
                    status: 'IC',
                    order_id: 70,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'EZSource Basic Operations Trainings (Can be completed after RFP Release)',
                    sub_title: null,
                    slug: 'ezsource-basic-operations-trainings-can-be-completed-after-rfp-release',
                    status: 'IC',
                    order_id: 71,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Implement Comments from Draft (post updates as you receive questions)',
            sub_title: null,
            slug: 'implement-comments-from-draft-post-updates-as-you-receive-questions',
            status: 'IC',
            order_id: 73,
            gate: 4,
            sub_gate: 1,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'First line supervisor review (May be done concurrently with legal review)',
            sub_title: null,
            slug: 'first-line-supervisor-review-may-be-done-concurrently-with-legal-review',
            status: 'IC',
            order_id: 74,
            gate: 4,
            sub_gate: 1,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'SSP & Business Clearance Legal Review',
            sub_title: null,
            slug: 'ssp-business-clearance-legal-review',
            status: 'IC',
            order_id: 75,
            gate: 4,
            sub_gate: 1,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'Fill out "Legal Review Request Form" and send to Legal for signature.',
                    sub_title: null,
                    slug: 'fill-out-legal-review-request-form-and-send-to-legal-for-signature',
                    status: 'IC',
                    order_id: 76,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Fill out Clearance Request Form and send to Legal for signature.',
                    sub_title: null,
                    slug: 'fill-out-clearance-request-form-and-send-to-legal-for-signature',
                    status: 'IC',
                    order_id: 77,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Send eSSS to Legal for signature.',
                    sub_title: null,
                    slug: 'send-esss-to-legal-for-signature',
                    status: 'IC',
                    order_id: 78,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Implement legal SSP & Business Clearance review comments',
            sub_title: null,
            slug: 'implement-legal-ssp-business-clearance-review-comments',
            status: 'IC',
            order_id: 79,
            gate: 4,
            sub_gate: 1,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'SSP Policy Review',
            sub_title: null,
            slug: 'ssp-policy-review',
            status: 'IC',
            order_id: 80,
            gate: 4,
            sub_gate: 1,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'SSP & Business Clearance Slides reviewed by PK/AMSO supervisors and branch chiefs',
            sub_title: null,
            slug: 'ssp-business-clearance-slides-reviewed-by-pkamso-supervisors-and-branch-chiefs',
            status: 'IC',
            order_id: 81,
            gate: 4,
            sub_gate: 1,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'SSP Approved',
            sub_title: null,
            slug: 'ssp-approved',
            status: 'IC',
            order_id: 82,
            gate: 4,
            sub_gate: 1,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Policy Review of Business Clearance',
            sub_title: null,
            slug: 'policy-review-of-business-clearance',
            status: 'IC',
            order_id: 83,
            gate: 4,
            sub_gate: 1,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'Clearance Check-in Sheet',
                    sub_title: null,
                    slug: 'clearance-checkin-sheet',
                    status: 'IC',
                    order_id: 84,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Clearance Request Form (Clearance Tracking # assigned by committee)',
                    sub_title: null,
                    slug: 'clearance-request-form-clearance-tracking-assigned-by-committee',
                    status: 'IC',
                    order_id: 85,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Contract Clearance Charts - Send to Ms. Sutton 72hrs before briefing.',
                    sub_title: null,
                    slug: 'contract-clearance-charts-send-to-ms-sutton-72hrs-before-briefing',
                    status: 'IC',
                    order_id: 86,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Policy Analyst will add comments to the HURT tool. PK to respond to comments.',
                    sub_title: null,
                    slug: 'policy-analyst-will-add-comments-to-the-hurt-tool-pk-to-respond-to-comments',
                    status: 'IC',
                    order_id: 87,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 1.0,
                    bus_days: 1.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Business Clearance Policy Review',
            sub_title: null,
            slug: 'business-clearance-policy-review',
            status: 'IC',
            order_id: 88,
            gate: 4,
            sub_gate: 1,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Implement Policy review comments',
            sub_title: null,
            slug: 'implement-policy-review-comments',
            status: 'IC',
            order_id: 89,
            gate: 4,
            sub_gate: 1,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Business Clearance',
            sub_title: null,
            slug: 'business-clearance',
            status: 'IC',
            order_id: 90,
            gate: 4,
            sub_gate: 1,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'RFP Release & Receipt of Proposals',
            sub_title: null,
            slug: 'rfp-release-receipt-of-proposals',
            status: 'IC',
            order_id: 91,
            gate: 4,
            sub_gate: 2,
            palt_plan: 30.0,
            bus_days: 30.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Release RFP ',
            sub_title: null,
            slug: 'release-rfp',
            status: 'IC',
            order_id: 92,
            gate: 4,
            sub_gate: 2,
            palt_plan: 30.0,
            bus_days: 30.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'EZSource Training - Instructor Lead (Complete all before propoal reciept)',
            sub_title: null,
            slug: 'ezsource-training-instructor-lead-complete-all-before-propoal-reciept',
            status: 'IC',
            order_id: 93,
            gate: 4,
            sub_gate: 2,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'How To Training for Source Selection Team',
                    sub_title: null,
                    slug: 'how-to-training-for-source-selection-team',
                    status: 'IC',
                    order_id: 94,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Past Performance Evaluation Team Training',
                    sub_title: null,
                    slug: 'past-performance-evaluation-team-training',
                    status: 'IC',
                    order_id: 95,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Red Flag Training',
                    sub_title: null,
                    slug: 'red-flag-training',
                    status: 'IC',
                    order_id: 96,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Phase II Training (as close to receipt of proposals as possible)',
                    sub_title: null,
                    slug: 'phase-ii-training-as-close-to-receipt-of-proposals-as-possible',
                    status: 'IC',
                    order_id: 97,
                    gate: 4,
                    sub_gate: 1,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Contractor Site Visit (if applicable)',
            sub_title: null,
            slug: 'contractor-site-visit-if-applicable',
            status: 'IC',
            order_id: 98,
            gate: 4,
            sub_gate: 2,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Receipt of Proposals',
            sub_title: null,
            slug: 'receipt-of-proposals',
            status: 'IC',
            order_id: 99,
            gate: 4,
            sub_gate: 2,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Evaluation of Offerors',
            sub_title: null,
            slug: 'evaluation-of-offerors',
            status: 'IC',
            order_id: 100,
            gate: 4,
            sub_gate: 3,
            palt_plan: 76.0,
            bus_days: 76.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Initial Proposal Evaluations ',
            sub_title: null,
            slug: 'initial-proposal-evaluations',
            status: 'IC',
            order_id: 101,
            gate: 4,
            sub_gate: 3,
            palt_plan: 20.0,
            bus_days: 20.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'Past Performance Evaluation',
                    sub_title: null,
                    slug: 'past-performance-evaluation',
                    status: 'IC',
                    order_id: 102,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Complete Unexpected Amendment',
                    sub_title: null,
                    slug: 'complete-unexpected-amendment',
                    status: 'IC',
                    order_id: 103,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Finish Reviewing Q&As',
                    sub_title: null,
                    slug: 'finish-reviewing-qas',
                    status: 'IC',
                    order_id: 104,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Make sure all changes found are incorporated',
                    sub_title: null,
                    slug: 'make-sure-all-changes-found-are-incorporated',
                    status: 'IC',
                    order_id: 105,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Legal Review',
                    sub_title: null,
                    slug: 'legal-review',
                    status: 'IC',
                    order_id: 106,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Release Amendment',
                    sub_title: null,
                    slug: 'release-amendment',
                    status: 'IC',
                    order_id: 107,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Reciept of Proposals',
                    sub_title: null,
                    slug: 'reciept-of-proposals',
                    status: 'IC',
                    order_id: 108,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Evaluation of Proposals',
                    sub_title: null,
                    slug: 'evaluation-of-proposals',
                    status: 'IC',
                    order_id: 109,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Price Evaluation',
                    sub_title: null,
                    slug: 'price-evaluation',
                    status: 'IC',
                    order_id: 110,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Technical Evaluation',
                    sub_title: null,
                    slug: 'technical-evaluation',
                    status: 'IC',
                    order_id: 111,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 2.0,
                    bus_days: 2.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Prepare Competitive Range Docs (see list:Complete Initial Ratings/Comp Range Brief/ENs)',
            sub_title: null,
            slug: 'prepare-competitive-range-docs-see-listcomplete-initial-ratingscomp-range-briefens',
            status: 'IC',
            order_id: 112,
            gate: 4,
            sub_gate: 3,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'Evaluation Notices',
                    sub_title: null,
                    slug: 'evaluation-notices',
                    status: 'IC',
                    order_id: 113,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Comp Range Charts - SSA',
                    sub_title: null,
                    slug: 'comp-range-charts-ssa',
                    status: 'IC',
                    order_id: 114,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'SSEB Report (Initial)',
                    sub_title: null,
                    slug: 'sseb-report-initial',
                    status: 'IC',
                    order_id: 115,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Competitive Range Decision Document (CRDD)',
                    sub_title: null,
                    slug: 'competitive-range-decision-document-crdd',
                    status: 'IC',
                    order_id: 116,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Exclusion Letters (if applicable)',
                    sub_title: null,
                    slug: 'exclusion-letters-if-applicable',
                    status: 'IC',
                    order_id: 117,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Notice to Offerors - Discussions',
                    sub_title: null,
                    slug: 'notice-to-offerors-discussions',
                    status: 'IC',
                    order_id: 118,
                    gate: 4,
                    sub_gate: 3,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Legal Review (Initial Evaluation Briefing (IEB) Competitive Range (CR) Briefing & ENs)',
            sub_title: null,
            slug: 'legal-review-initial-evaluation-briefing-ieb-competitive-range-cr-briefing-ens',
            status: 'IC',
            order_id: 119,
            gate: 4,
            sub_gate: 3,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Strategic pause for Thanksgiving Holiday - no one expects reviews to be done this week',
            sub_title: null,
            slug: 'strategic-pause-for-thanksgiving-holiday-no-one-expects-reviews-to-be-done-this-week',
            status: 'IC',
            order_id: 120,
            gate: 4,
            sub_gate: 3,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Policy Review (Comp Range Docs & ENs)',
            sub_title: null,
            slug: 'policy-review-comp-range-docs-ens',
            status: 'IC',
            order_id: 121,
            gate: 4,
            sub_gate: 3,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'PK/AMSO Supervisor and Branch Chief Reviews (Initial Evaluation Briefing (IEB) Competitive Range (CR) Briefing & ENs)',
            sub_title: null,
            slug: 'pkamso-supervisor-and-branch-chief-reviews-initial-evaluation-briefing-ieb-competitive-range-cr-briefing-ens',
            status: 'IC',
            order_id: 122,
            gate: 4,
            sub_gate: 3,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Resolve Comments & Schedule Brief to SSA',
            sub_title: null,
            slug: 'resolve-comments-schedule-brief-to-ssa',
            status: 'IC',
            order_id: 123,
            gate: 4,
            sub_gate: 3,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Competitive Range Brief to SSA (Have signing slides) (Schedule at legal review)',
            sub_title: null,
            slug: 'competitive-range-brief-to-ssa-have-signing-slides-schedule-at-legal-review',
            status: 'IC',
            order_id: 124,
            gate: 4,
            sub_gate: 3,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Release Evaluation Notices (EN)',
            sub_title: null,
            slug: 'release-evaluation-notices-en',
            status: 'IC',
            order_id: 125,
            gate: 4,
            sub_gate: 3,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Receipt of ENs',
            sub_title: null,
            slug: 'receipt-of-ens',
            status: 'IC',
            order_id: 126,
            gate: 4,
            sub_gate: 3,
            palt_plan: 14.0,
            bus_days: 14.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Evaluate ENs',
            sub_title: null,
            slug: 'evaluate-ens',
            status: 'IC',
            order_id: 127,
            gate: 4,
            sub_gate: 3,
            palt_plan: 15.0,
            bus_days: 15.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Prepare FPR Request',
            sub_title: null,
            slug: 'prepare-fpr-request',
            status: 'IC',
            order_id: 128,
            gate: 4,
            sub_gate: 4,
            palt_plan: 93.0,
            bus_days: 93.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Prepare FPR Request',
            sub_title: null,
            slug: 'prepare-fpr-request',
            status: 'IC',
            order_id: 129,
            gate: 4,
            sub_gate: 4,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Prepare FPR Docs for Reviews (See list)',
            sub_title: null,
            slug: 'prepare-fpr-docs-for-reviews-see-list',
            status: 'IC',
            order_id: 130,
            gate: 4,
            sub_gate: 4,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'FPR Letters to Offerors',
                    sub_title: null,
                    slug: 'fpr-letters-to-offerors',
                    status: 'IC',
                    order_id: 131,
                    gate: 4,
                    sub_gate: 4,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'FPR Briefing Charts - SSA',
                    sub_title: null,
                    slug: 'fpr-briefing-charts-ssa',
                    status: 'IC',
                    order_id: 132,
                    gate: 4,
                    sub_gate: 4,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'SSEB Report (Interim)',
                    sub_title: null,
                    slug: 'sseb-report-interim',
                    status: 'IC',
                    order_id: 133,
                    gate: 4,
                    sub_gate: 4,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Legal Review',
            sub_title: null,
            slug: 'legal-review',
            status: 'IC',
            order_id: 134,
            gate: 4,
            sub_gate: 4,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'PK/AMSO Supervisor and Branch Chief Reviews',
            sub_title: null,
            slug: 'pkamso-supervisor-and-branch-chief-reviews',
            status: 'IC',
            order_id: 135,
            gate: 4,
            sub_gate: 4,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Policy Review',
            sub_title: null,
            slug: 'policy-review',
            status: 'IC',
            order_id: 136,
            gate: 4,
            sub_gate: 4,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Resolve Comments & Schedule Clearance - FPR',
            sub_title: null,
            slug: 'resolve-comments-schedule-clearance-fpr',
            status: 'IC',
            order_id: 137,
            gate: 4,
            sub_gate: 4,
            palt_plan: 4.0,
            bus_days: 4.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Contract Clearance (FPR Request and Finalize FPR Docs)',
            sub_title: null,
            slug: 'contract-clearance-fpr-request-and-finalize-fpr-docs',
            status: 'IC',
            order_id: 138,
            gate: 4,
            sub_gate: 4,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'FPR Letters to Offerors',
                    sub_title: null,
                    slug: 'fpr-letters-to-offerors',
                    status: 'IC',
                    order_id: 139,
                    gate: 4,
                    sub_gate: 4,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'FPR Briefing Charts - SSA',
                    sub_title: null,
                    slug: 'fpr-briefing-charts-ssa',
                    status: 'IC',
                    order_id: 140,
                    gate: 4,
                    sub_gate: 4,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'SSEB Report',
                    sub_title: null,
                    slug: 'sseb-report',
                    status: 'IC',
                    order_id: 141,
                    gate: 4,
                    sub_gate: 4,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Schedule Brief to SSA',
            sub_title: null,
            slug: 'schedule-brief-to-ssa',
            status: 'IC',
            order_id: 142,
            gate: 4,
            sub_gate: 4,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Combined Contract Clearance/SSA Approval Brief',
            sub_title: null,
            slug: 'combined-contract-clearancessa-approval-brief',
            status: 'IC',
            order_id: 143,
            gate: 4,
            sub_gate: 4,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Release FPR',
            sub_title: null,
            slug: 'release-fpr',
            status: 'IC',
            order_id: 144,
            gate: 4,
            sub_gate: 4,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'FPR Receipt',
            sub_title: null,
            slug: 'fpr-receipt',
            status: 'IC',
            order_id: 145,
            gate: 4,
            sub_gate: 4,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Evaluate FPRs',
            sub_title: null,
            slug: 'evaluate-fprs',
            status: 'IC',
            order_id: 146,
            gate: 4,
            sub_gate: 4,
            palt_plan: 10.0,
            bus_days: 10.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Prepare for Final Award',
            sub_title: null,
            slug: 'prepare-for-final-award',
            status: 'IC',
            order_id: 147,
            gate: 4,
            sub_gate: 4,
            palt_plan: 19.0,
            bus_days: 19.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Prepare Final Award Docs (see list  below)',
            sub_title: null,
            slug: 'prepare-final-award-docs-see-list-below',
            status: 'IC',
            order_id: 148,
            gate: 4,
            sub_gate: 4,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'Contract Award (CON-IT or ACPS)',
                    sub_title: null,
                    slug: 'contract-award-conit-or-acps',
                    status: 'IC',
                    order_id: 149,
                    gate: 4,
                    sub_gate: 4,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'SSEB Report (Final)',
                    sub_title: null,
                    slug: 'sseb-report-final',
                    status: 'IC',
                    order_id: 150,
                    gate: 4,
                    sub_gate: 4,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: "SSAC Report (not req'd if using LPTA)",
                    sub_title: null,
                    slug: 'ssac-report-not-reqd-if-using-lpta',
                    status: 'IC',
                    order_id: 151,
                    gate: 4,
                    sub_gate: 4,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Source Selection Decision Document (SSDD)',
                    sub_title: null,
                    slug: 'source-selection-decision-document-ssdd',
                    status: 'IC',
                    order_id: 152,
                    gate: 4,
                    sub_gate: 4,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Award Decision Charts -SSA',
                    sub_title: null,
                    slug: 'award-decision-charts-ssa',
                    status: 'IC',
                    order_id: 153,
                    gate: 4,
                    sub_gate: 4,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Legal Review',
            sub_title: null,
            slug: 'legal-review',
            status: 'IC',
            order_id: 154,
            gate: 4,
            sub_gate: 4,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'PK/AMSO Supervisor and Branch Chief Reviews',
            sub_title: null,
            slug: 'pkamso-supervisor-and-branch-chief-reviews',
            status: 'IC',
            order_id: 155,
            gate: 4,
            sub_gate: 4,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Policy Review',
            sub_title: null,
            slug: 'policy-review',
            status: 'IC',
            order_id: 156,
            gate: 4,
            sub_gate: 4,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Resolve Comments & Schedule Clearance',
            sub_title: null,
            slug: 'resolve-comments-schedule-clearance',
            status: 'IC',
            order_id: 157,
            gate: 4,
            sub_gate: 4,
            palt_plan: 6.0,
            bus_days: 6.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Contract Clearance (Award Decision) (See list below)',
            sub_title: null,
            slug: 'contract-clearance-award-decision-see-list-below',
            status: 'IC',
            order_id: 158,
            gate: 4,
            sub_gate: 4,
            palt_plan: 6.0,
            bus_days: 6.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
            tasks: [
                {
                    title: 'Clearance Check-in Sheet',
                    sub_title: null,
                    slug: 'clearance-checkin-sheet',
                    status: 'IC',
                    order_id: 159,
                    gate: 4,
                    sub_gate: 4,
                    palt_plan: 6.0,
                    bus_days: 6.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Clearance Request Form',
                    sub_title: null,
                    slug: 'clearance-request-form',
                    status: 'IC',
                    order_id: 160,
                    gate: 4,
                    sub_gate: 4,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
                {
                    title: 'Contract Clearance Charts',
                    sub_title: null,
                    slug: 'contract-clearance-charts',
                    status: 'IC',
                    order_id: 161,
                    gate: 4,
                    sub_gate: 4,
                    palt_plan: 0.0,
                    bus_days: 0.0,
                    start_date: null,
                    end_date: null,
                    ssp_date: null,
                    comments: null,
                    poc: null,
                },
            ],
        },
        {
            title: 'Schedule SSA Decision Brief',
            sub_title: null,
            slug: 'schedule-ssa-decision-brief',
            status: 'IC',
            order_id: 162,
            gate: 4,
            sub_gate: 4,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Combined Contract Clearance & SSA Decision Briefing',
            sub_title: null,
            slug: 'combined-contract-clearance-ssa-decision-briefing',
            status: 'IC',
            order_id: 163,
            gate: 4,
            sub_gate: 4,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'EEO Pre-Award Notice email sent.',
            sub_title: null,
            slug: 'eeo-preaward-notice-email-sent',
            status: 'IC',
            order_id: 164,
            gate: 4,
            sub_gate: 4,
            palt_plan: 6.0,
            bus_days: 6.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Small Business Challenge Letters (closes 5 business days after notification)',
            sub_title: null,
            slug: 'small-business-challenge-letters-closes-5-business-days-after-notification',
            status: 'IC',
            order_id: 165,
            gate: 4,
            sub_gate: 4,
            palt_plan: 6.0,
            bus_days: 6.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Prepare for Final Award',
            sub_title: null,
            slug: 'prepare-for-final-award',
            status: 'IC',
            order_id: 166,
            gate: 4,
            sub_gate: 5,
            palt_plan: 33.0,
            bus_days: 33.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Prepare for Final Award',
            sub_title: null,
            slug: 'prepare-for-final-award',
            status: 'IC',
            order_id: 167,
            gate: 4,
            sub_gate: 5,
            palt_plan: 2.0,
            bus_days: 2.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Congressional Notification - 1279 Report (Send 3 days prior to contract award)',
            sub_title: null,
            slug: 'congressional-notification-1279-report-send-3-days-prior-to-contract-award',
            status: 'IC',
            order_id: 168,
            gate: 4,
            sub_gate: 5,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Contract Award notice emailed in accordance with FAR 15.503',
            sub_title: null,
            slug: 'contract-award-notice-emailed-in-accordance-with-far-15503',
            status: 'IC',
            order_id: 169,
            gate: 4,
            sub_gate: 5,
            palt_plan: 1.0,
            bus_days: 1.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: '10 day protest window without CICA stay starts',
            sub_title: null,
            slug: '10-day-protest-window-without-cica-stay-starts',
            status: 'IC',
            order_id: 170,
            gate: 4,
            sub_gate: 5,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Debrief requests due within 3 Calendar days of award notice IAW FAR 15.506',
            sub_title: null,
            slug: 'debrief-requests-due-within-3-calendar-days-of-award-notice-iaw-far-15506',
            status: 'IC',
            order_id: 171,
            gate: 4,
            sub_gate: 5,
            palt_plan: 3.0,
            bus_days: 3.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Debrief within 5 Calendar days after receipt of written debrief request IAW FAR 15.506',
            sub_title: null,
            slug: 'debrief-within-5-calendar-days-after-receipt-of-written-debrief-request-iaw-far-15506',
            status: 'IC',
            order_id: 172,
            gate: 4,
            sub_gate: 5,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Questions due 2 Business days after debrief. \nIAW Section 818(B) of the 2018 NDAA',
            sub_title: null,
            slug: 'questions-due-2-business-days-after-debrief-iaw-section-818b-of-the-2018-ndaa',
            status: 'IC',
            order_id: 173,
            gate: 4,
            sub_gate: 5,
            palt_plan: 2.0,
            bus_days: 2.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Legal Review Questions',
            sub_title: null,
            slug: 'legal-review-questions',
            status: 'IC',
            order_id: 174,
            gate: 4,
            sub_gate: 5,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: "Gov't response to questions within 5 Business days. This event concludes the debriefing and begins the five-day protest window. IAW Section 818(B) of the 2018 NDAA",
            sub_title: null,
            slug: 'govt-response-to-questions-within-5-business-days-this-event-concludes-the-debriefing-and-begins-the-fiveday-protest-window-iaw-section-818b-of-the-2018-ndaa',
            status: 'IC',
            order_id: 175,
            gate: 4,
            sub_gate: 5,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: '5 day protest window with CICA stay starts.',
            sub_title: null,
            slug: '5-day-protest-window-with-cica-stay-starts',
            status: 'IC',
            order_id: 176,
            gate: 4,
            sub_gate: 5,
            palt_plan: 5.0,
            bus_days: 5.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Confirm Protests Status @ https://www.gao.gov/legal/bid-protests/search',
            sub_title: null,
            slug: 'confirm-protests-status',
            status: 'IC',
            order_id: 177,
            gate: 4,
            sub_gate: 5,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Delivery of Safety Plan etc. ',
            sub_title: null,
            slug: 'delivery-of-safety-plan-etc',
            status: 'IC',
            order_id: 178,
            gate: 4,
            sub_gate: 5,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Post Award Conference - CLIN 1001 (FA820121R0007)(FAR 42.503)',
            sub_title: null,
            slug: 'post-award-conference-clin-1001-fa820121r0007far-42503',
            status: 'IC',
            order_id: 179,
            gate: 4,
            sub_gate: 5,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Create DD Form 1484 & file in Tab 68.',
            sub_title: null,
            slug: 'create-dd-form-1484-file-in-tab-68',
            status: 'IC',
            order_id: 180,
            gate: 4,
            sub_gate: 5,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
        {
            title: 'Tranfer e-files from: PZI Pre Award to: Contract Administration',
            sub_title: null,
            slug: 'tranfer-efiles-from-pzi-pre-award-to-contract-administration',
            status: 'IC',
            order_id: 181,
            gate: 4,
            sub_gate: 5,
            palt_plan: 0.0,
            bus_days: 0.0,
            start_date: null,
            end_date: null,
            ssp_date: null,
            comments: null,
            poc: null,
        },
    ],
}

export default baseContract
