import type { Task } from '@/types/ContractData.type'

const basicContract: Task[] = [
    {
        id: 101,
        title: 'Identify / Validate Need',
        sub_title: 'Subtitle Text Here',
        slug: 'identify-validate-need',
        status: 'IP',
        task_id: null,
        contract_id: 21,
        order_id: 1,
        gate: 1,
        subgate: null,
        palt_plan: null,
        bus_days: null,
        start_date: null,
        end_date: null,
        ssp_date: null,
        poc: null,
        comments: null,
        tasks: [
            {
                id: 102,
                title: 'Identify issues, requirements, needs',
                sub_title: '',
                slug: 'identify-issues-requirements-needs',
                status: 'CP',
                task_id: 101,
                contract_id: 21,
                order_id: 2,
                gate: 1,
                subgate: null,
                palt_plan: 5,
                bus_days: 3,
                start_date: new Date('2022-11-12'),
                end_date: new Date('2022-11-18'),
                ssp_date: new Date('2022-11-20'),
                poc: {
                    id: 12,
                    first_name: 'Kailey',
                    last_name: 'Norman',
                    email: 'kailey.norman@hillbilly.gov',
                    prefix: 'Ms',
                    title: {
                        id: 123,
                        title: 'SSEB Chairperson / PM',
                        department: 'Department of Somthing Here',
                    },
                },
                comments: null,
                tasks: null,
            },
            {
                id: 103,
                title: 'Establish need and technical review/ dates',
                sub_title: '',
                slug: 'establish-need-and-technical-review-dates',
                status: 'CP',
                task_id: 101,
                contract_id: 21,
                order_id: 3,
                gate: 1,
                subgate: null,
                palt_plan: 5,
                bus_days: 3,
                start_date: new Date('2022-11-12'),
                end_date: new Date('2022-11-18'),
                ssp_date: new Date('2022-11-20'),
                poc: {
                    id: 12,
                    first_name: 'Kailey',
                    last_name: 'Norman',
                    email: 'kailey.norman@hillbilly.gov',
                    prefix: 'Ms',
                    title: {
                        id: 123,
                        title: 'SSEB Chairperson / PM',
                        department: 'Department of Somthing Here',
                    },
                },
                comments: 'Some comments about this item here',
                tasks: null,
            },
            {
                id: 104,
                title: 'Organic vs. contract',
                sub_title: '',
                slug: 'organic-vs-contract',
                status: 'IP',
                task_id: 101,
                contract_id: 21,
                order_id: 4,
                gate: 1,
                subgate: null,
                palt_plan: 5,
                bus_days: 3,
                start_date: new Date('2022-11-12'),
                end_date: new Date('2022-11-18'),
                ssp_date: new Date('2022-11-20'),
                poc: {
                    id: 12,
                    first_name: 'Kailey',
                    last_name: 'Norman',
                    email: 'kailey.norman@hillbilly.gov',
                    prefix: 'Ms',
                    title: {
                        id: 123,
                        title: 'SSEB Chairperson / PM',
                        department: 'Department of Somthing Here',
                    },
                },
                comments: 'Some comments about this item here',
                tasks: null,
            },
            {
                id: 105,
                title: '50/50',
                sub_title: 'Document showing concurrence from DV',
                slug: '50-50-document-showing-concurrence-from-dv',
                status: 'IC',
                task_id: 101,
                contract_id: 21,
                order_id: 5,
                gate: 1,
                subgate: null,
                palt_plan: 5,
                bus_days: 3,
                start_date: new Date('2022-11-12'),
                end_date: new Date('2022-11-18'),
                ssp_date: new Date('2022-11-20'),
                poc: {
                    id: 12,
                    first_name: 'Kailey',
                    last_name: 'Norman',
                    email: 'kailey.norman@hillbilly.gov',
                    prefix: 'Ms',
                    title: {
                        id: 123,
                        title: 'SSEB Chairperson / PM',
                        department: 'Department of Somthing Here',
                    },
                },
                comments: null,
                tasks: null,
            },
        ],
    },
    {
        id: 106,
        title: "Req't Meeting with Stakeholders",
        sub_title: 'Another Subtitle Text Here',
        slug: 'reqt-meeting-with-stakeholders',
        status: 'IC',
        task_id: null,
        contract_id: 21,
        order_id: 6,
        gate: 4,
        subgate: 1,
        palt_plan: 2,
        bus_days: 2,
        start_date: new Date('2022-11-12'),
        end_date: new Date('2022-11-18'),
        ssp_date: new Date('2022-11-20'),
        poc: {
            id: 13,
            first_name: 'Joseph',
            last_name: 'Laing',
            email: 'joseph.laing@hillbilly.gov',
            prefix: 'Mr',
            title: {
                id: 124,
                title: 'Contract Specialist',
                department: 'Department of Somthing Else',
            },
        },
        comments: 'Some comments about this item here',
        tasks: null,
    },
]

export default basicContract
