import type { ContractBuild } from '@/types/ContractData.type'

export const contractBase: ContractBuild = {
    title: '',
    sub_title: '',
    slug: '',
    type: '',
    ucid: '',
    status: 'IC',
    value: 0,
    cycle_code: null,
    need_date: null,
    award_date: null,
    start_date: null,
    pop_date: null,
    g_o_p: 0,
    g_t_p: 0,
    g_tr_p: 0,
    g_fr_o_p: 0,
    g_fr_t_p: 0,
    g_fr_tr_p: 0,
    g_fr_fr_p: 0,
    g_fr_fv_p: 0,
    pocs: [] as number[],
    ss_leads: [] as number[],
    ssa: null,
    caa: null,
    sdo: null,
    pco: null,
    buyer: null,
    admin_pco: null,
    admin_buyer: null,
    comments: null,
    tasks: [],
}
